- name: ansible varaible data types
  hosts: localhost
  vars:
  - AGE: 29
  - NAME: Mahesh
  - isDevOps: true
  - skills: #list
    - DevOps
    - AWS
    - Docker
  - Experience: #map
     Devops: 7
     AWS: 7
     Docker: 7
  tasks:
   - name: print variables names
     ansible.builtin.debug:
     msg: "{{AGE}}"
   - name: print variables names
     ansible.builtin.debug:
     msg: "{{NAME}}"
   - name: print variables names
     ansible.builtin.debug:
     msg: "{{isDevOps}}"
   - name: print variables names
     ansible.builtin.debug:
     msg: "{{skills}}"
   - name: print variables names
     ansible.builtin.debug:
     msg: "{{Experience}}"