- name: Setup NPM Source
  hosts: mongodb
  become: yes
  tasks:
    - name: Install curl
      ansible.builtin.package:
        name: curl
        state: present

    - name: Download and Run Node.js Setup Script
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
    
    - name: Install nodejs
      ansible.builtin.yum:
        name: nodejs
        state: installed
    
    - name: Check user exist or not
      ansible.builtin.command: id roboshop
      register: out
      ignore_errors: true

    - when: out.rc != 0
      name: create user roboshop
      become: yes
      ansible.builtin.user:
       name: roboshop
    
    - name: check /app directory exists or not
      ansible.builtin.stat:
       path: /app
      register: directory

    - name: print dir status
      ansible.builtin.debug:
       msg: "output: {{directory}}"
    
    - when: directory.stat.exists == False
      name: create /app directory
      ansible.builtin.file:
        path: /app  # Change this path as needed
        state: directory
    
    - name: Download catalogue artifact
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip
    
    - name: extract catalogue artifact
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
    
    - name: Install dependecies
      ansible.builtin.command: npm install
      args:
       chdir: /app
    
    - name: copy catalogue service
      ansible.builtin.service:
       src: catalogue.service
       dest: /etc/systemd/system/catalogue.service
    
    - name: Reload daemon
      ansible.builtin.systemd:
       daemon_reload: yes
    
    - name: copy mongo rep to yum.repo.d
      ansible.builtin.copy:
       src: mongodb.repo
       dest: /etc/yum.repos.d/mongo.repo
    
    - name: Install mongodb
      ansible.builtin.yum:
       name: mongodb-org
       state: installed
    
    - name: load catalogue data
      ansible.builtin.command: mongo --host mongodb </app/schema/catalogue.js
    
    - name: Restart catalogue service
      ansible.builtin.systemd:
       name: catalogue
       state: restarted
       enabled: yes
      
    

      


      