- name: Setup NPM Source
  hosts: localhost
  become: yes
  tasks:
    - name: Install curl
      ansible.builtin.package:
        name: curl
        state: present

    - name: Download and Run Node.js Setup Script
      ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash