- name: create user
  hosts: localhost
  tasks:
  - name: check user exist or not
   #when you want ot run linux cmds directly, if ansible module not avail
   #when user does not exist , ansible treating it as failure.
   #We want to proceed with ignorig the error.
    ansible.builtin.command: id roboshop
    register: output #var name
    ignore_errors: true
  - name: print the cmd output
    ansible.builtin.debug:
     msg: "output is: {{output}}"

  - name: print the exit status
    ansible.builtin.debug:
     msg: "{{output.rc}}"
    
  - name: Create user roboshop
    become: yes
    ansible.builtin.user:
     name: user
    when: output.rc != 0
     #exit status -> rc:1