- name: Install mongodb component
  hosts: mongodb
  become: yes
  tasks:
   - name: copy mongo rep to yum.repo.d
     ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

   - name: Install mongodb
     ansible.builtin.yum:
      name: mongodb-org
      state: installed

   - name: Start and enable mongodb
     ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

   - name: enable remote connection to mongodb
     ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: 'f127.0.0.1'
        replace: '0.0.0.0'
        
   - name: restart mongodb
     ansible.builtin.service:
      name: mongod
      state: restarted
      