- name: variables in ansible
  hosts: mongodb
  #playlevel variables
  vars:
    COURSE: Devops
    TRAINER: Shiva
    DURATION: 3 months
  
  
  tasks:
  - name: Print hello world
    ansible.builtin.debug:
     msg: "Hello,Im learning ansible"
  - name: Refer Variables
    ansible.builtin.debug:
     msg: "Hello,Im learning {{COURSE}}, Trainer is {{TRAINER}},Duration is {{DURATION}}"