- name: Vars at task level
  hosts: localhost

  vars:
  - money: "10K Rs"
    land: "100 hect"

  tasks:
  - name: Inherit values from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"

  - name: Inherit values from play and override
    vars:
     - money: "10K Rs"
       land: "100 hect"
       houses: "3 houses"
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}, houses: {{houses}}" 